### ISSUE TITLE
Callback fires multiple times

### ISSUE THREAD

**Issue by ghost** [skorecky/Add-Clear#15]
If you apply addClear to multiple elements the callback is apply X times as it is bound to the close button but not in context to its instance:

```javascript
$("a[href='#clear']").click(function(e) {...
```

**Comment by skorecky** [comment]
As a quick fix you could try adding `e.stopPropagation()`

**Comment by beardfu** [comment]
Cheers for the quick reply!

I've sorted it by adding the .click() after the .css() on $this.next within the init.

**Comment by skorecky** [comment]
Yeah, that will probably be the long term fix. Thanks for letting me know.
