### ISSUE TITLE
Demo Page working for me in Chrome or Firefox, but does in IE (Win8 PC)

### ISSUE THREAD

**Issue by Pakuku** [skorecky/Add-Clear#16]
This is down to... 

Blocked loading mixed active content "http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"

...which simply means the browser is invoking a denial of content due to mixed https and http in the page.  Remove 'http:' from the src/path for jquery.min and your demo page will provide more clicks through to Github.

**Comment by skorecky** [comment]
fixed
