### ISSUE TITLE
autocomplete

### ISSUE THREAD

**Issue by m1cah** [skorecky/Add-Clear#20]
I was playing around with your plugin for form data when I noticed a bug. When autocomplete is on such that when you load the page and the input box is already populated, pressing the 'x' button removes the pre-populated text from view, yet still allows you to submit the form as if the text had not been deleted.

**Comment by m1cah** [comment]
Update: This is caused since I am using AngularJS, which does not recognize when the JQuery is executed. Fixed via a workaround/hack.

**Comment by dalexisv83** [comment]
@m1cah what was your workaround? I'm also using this on an angular project.

**Comment by m1cah** [comment]
If I remember correctly, I ended up not using Angular for this part of the project. Instead, I used a regular jQuery form to handle the data. Sorry I can't be of more help.
