### ISSUE TITLE
Couple of suggestions for improving the project

### ISSUE THREAD

**Issue by cageygee3** [skorecky/Add-Clear#23]
I'm interested in using add-clear in my project, but there are a couple enhancements I'd need to have first before it would work for me.

First, the clear button competes with the clear button that already exists in IE11 and Edge, creating a wonky scenario with one 'x' on top of the other. I think it'd be great if your code could disable the built-in clear button automatically (just for those browsers), but if you'd rather make that an option that defaults to false, I'd be happy with that too. Some quick research turned this up:

https://developer.mozilla.org/en-US/docs/Web/CSS/::-ms-clear

Second, if you fill the field with text, the 'x' is displayed on top of the text, which, again, looks bad. Adding padding-right of 20px seems to fix the issue nicely. Again, I'll leave it up to you if you want to make this default behavior or an option that defaults to false. There could be some interaction between this option and the first one I suggested, as the Microsoft browsers automatically add padding so their built-in clear button doesn't run into this problem.

What do you think?

**Comment by skorecky** [comment]
I think these are excellent suggestions, however my time is limited these
days so it's easier for me to just deal with pull requests. However if you
don't have the time yourself for a pull request or lack technical ability I
will try to add these suggestions myself but it will probably take a bit
longer. Thanks!

**Comment by cageygee3** [comment]
Quite understandable, so I'll take a look and see what I can do. :smile:

**Comment by cageygee3** [comment]
It turns out the built-in clear button in the Microsoft browsers can't be disabled through JavaScript, only by using a proprietary, vendor-specific CSS pseudo-class, so I don't think there's anything we can do about that here. I'll have to add that pseudo-class to my project's stylesheets. I can add a blurb about that to the README file.

I added a new option (with a reasonable default value) for padding so the clear button doesn't sit on top of the entered text. I'll submit a pull request for all of this shortly.

**Comment by skorecky** [comment]
Thanks for the pull request!

**Comment by cageygee3** [comment]
My pleasure! How often do you do releases?

**Comment by skorecky** [comment]
Not super often, but I have a couple in there now so I should do one soon.
Maybe tomorrow :)

**Comment by cageygee3** [comment]
OK great, would love to see a new release so I can use this in my project. :smile:

**Comment by skorecky** [comment]
Pushed the update
